### ISSUE TITLE
Bug in exampleapp4?  

### ISSUE THREAD

**Issue by Beagle123** [cedlemo/ruby-gtk3-tutorial#1]
Hi seldemo:

I'm reading your tutorial, and trying to understand all this stuff.  When I tried running the examples, the first several worked, but then I got this on exampleapp4.rb:

eric@eric-18-5010la:~/vrp/cedlimo/samples$ ruby exampleapp4.rb 
/home/eric/.rvm/gems/ruby-2.3.0/gems/gobject-introspection-3.0.8/lib/gobject-introspection/loader.rb: line 551
   Gtk-DEBUG **:Connecting to session manager
exampleapp4.rb:66:in `block in initialize': undefined method`set_accels_for_action' for #<ExampleApp:0x1c83d30 ptr=0xf5c210>
Did you mean?  set_trace_func
     from /home/eric/.rvm/gems/ruby-2.3.0/gems/gobject-introspection-3.0.8/lib/gobject-introspection/loader.rb:551:in `invoke'
     from /home/eric/.rvm/gems/ruby-2.3.0/gems/gobject-introspection-3.0.8/lib/gobject-introspection/loader.rb:551:in`block in define_method'
     from exampleapp4.rb:103:in `<main>'
eric@eric-18-5010la:~/vrp/cedlimo/samples$

**Comment by cedlemo** [comment]
Hi Beagle123,

This tutorial has been merged in the Ruby-GNOME2 project here https://github.com/ruby-gnome2/ruby-gnome2/tree/master/gtk3/sample/tutorial. The version in Ruby-GNOME2 project is more up to date. So you really should try the Ruby-GNOME2 version of the tutorial and create an issue there if the problem remains. 

Thanks,
 I let you close and sorry I should have indicate that this is no the up to date version (or maybe destroy this repo)

cedlemo
